# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Deploy website
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: |   
        git config --global remote.origin.url "https://keepdying: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@github.com/keepdying/firestorm-rio"
        git config --global user.name "Github Actions"
        git config --global user.email "yunusemre34tr@gmail.com"
    - run: npm ci
    - run: npm run deploy
